Repository BinaryStudioAcademy/bsa-2018-hedonist, pull requests merged in 2018-08, with the labels that each got.

#8 Add prettus repository package
  config/repository.php
Labels: bug

#10 IMPLEMENT BASE ARCHITECTURE INTERFACES
  app/Actions/ActionInterface.php
  app/Actions/RequestInterface.php
  app/Actions/ResponseInterface.php
Labels: enhancement

#9 Clockwork : add clockwork (php dev tool)
  composer.json
  composer.lock
Labels: enhancement

#17 likes: add likes migration & model
  app/Entities/Likes.php
  database/migrations/2018_08_03_093349_create_likes_table.php
Labels: enhancement

#16 Feature/implement place category
  app/Entities/Place/PlaceCategory.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/Place/PlaceCategoryRepository.php
  app/Repositories/Place/PlaceCategoryRepositoryInterface.php
  database/factories/PlaceCategoryFactory.php
  database/migrations/2018_08_02_225416_create_place_categories_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/PlaceCategoryTableSeeder.php
Labels: enhancement

#19 Implemented places' features
  app/Entities/Place/PlaceFeature.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/Place/PlaceFeatureRepository.php
  app/Repositories/Place/PlaceFeatureRepositoryInterface.php
  config/app.php
  database/factories/PlacesFeaturesFactory.php
  database/migrations/2018_08_03_053907_create_places_features_table.php
  database/migrations/2018_08_03_061008_create_places_places_features_table.php
  database/seeds/PlacesFeaturesTableSeeder.php
Labels: enhancement

#31 ApiController: fixes in namespace and use mention
  app/Http/Controllers/Api/ApiController.php
Labels: bug

#29 Feature/place category add soft delete
  app/Entities/Place/PlaceCategory.php
  database/migrations/2018_08_02_225416_create_place_categories_table.php
  database/migrations/2018_08_03_093349_create_likes_table.php
Labels: enhancement

#27 likes: remove length likeable_type.
  database/migrations/2018_08_03_093349_create_likes_table.php
Labels: enhancement

#35 Fix/place feature seed factory
  database/factories/PlacesFeaturesFactory.php
  database/seeds/PlacesFeaturesTableSeeder.php
Labels: bug

#41 Feature/implement ratings
  app/Entities/Place/PlaceRating.php
  database/factories/PlaceRatingFactory.php
  database/migrations/2018_08_06_065718_create_place_rating_table.php
Labels: enhancement

#44 Fix factory's define (from City to Language) model.
  database/factories/LanguageFactory.php
Labels: bug

#51 Hotfix/places: fix namespaces
  app/Entities/Place/Place.php
  database/factories/PlaceFactory.php
Labels: bug

#53 Route's JWT group correction.
  routes/api.php
Labels: invalid

#37 Feature/places special feature api endpoints
  app/Actions/Place/SpecialFeature/CreatePlaceFeatureAction.php
  app/Actions/Place/SpecialFeature/CreatePlaceFeatureRequest.php
  app/Actions/Place/SpecialFeature/CreatePlaceFeatureResponse.php
  app/Actions/Place/SpecialFeature/DeletePlaceFeatureAction.php
  app/Actions/Place/SpecialFeature/DeletePlaceFeatureRequest.php
  app/Actions/Place/SpecialFeature/DeletePlaceFeatureResponse.php
  app/Actions/Place/SpecialFeature/Exceptions/PlaceFeatureNotFoundException.php
  app/Actions/Place/SpecialFeature/GetCollectionPlaceFeatureAction.php
  app/Actions/Place/SpecialFeature/GetCollectionPlaceFeatureRequest.php
  app/Actions/Place/SpecialFeature/GetCollectionPlaceFeatureResponse.php
  app/Actions/Place/SpecialFeature/ReadPlaceFeatureAction.php
  app/Actions/Place/SpecialFeature/ReadPlaceFeatureRequest.php
  app/Actions/Place/SpecialFeature/ReadPlaceFeatureResponse.php
  app/Http/Controllers/Api/Places/PlaceFeaturesController.php
  app/Http/Requests/JsonRequest.php
  app/Http/Requests/Place/SpecialFeature/CreateSpecialFeatureHttpRequest.php
  database/factories/PlacesFeaturesFactory.php
  database/seeds/DatabaseSeeder.php
  routes/api.php
  tests/Feature/Api/Place/PlaceFeaturesControllerTest.php
  tests/JwtTestCase.php
  tests/Unit/Routes/PlacesFeatureRoutesTest.php
Labels: enhancement

#59 hotfix: fix user namespace for Like
  app/Entities/Like/Like.php
Labels: bug

#48 Feature/place categories tags
  app/Entities/Place/PlaceCategory.php
  app/Entities/Place/PlaceCategoryTag.php
  app/Repositories/Place/PlaceCategoryTagRepository.php
  app/Repositories/Place/PlaceCategoryTagRepositoryInterface.php
  database/factories/PlaceCategoriesTagsFactory.php
  database/migrations/2018_08_06_110220_create_place_categories_tags_table.php
  database/migrations/2018_08_06_111954_create_place_category_place_tag_table.php
  database/seeds/PlaceCategoriesTagsSeeder.php
Labels: enhancement

#52 Feature/place like dislike api endpoints
  app/Actions/Dislike/DislikePlaceAction.php
  app/Actions/Dislike/DislikePlaceRequest.php
  app/Actions/Dislike/DislikePlaceResponse.php
  app/Actions/Like/LikePlaceAction.php
  app/Actions/Like/LikePlaceRequest.php
  app/Actions/Like/LikePlaceResponse.php
  app/Entities/UserList/UserList.php
  app/Exceptions/Place/PlaceNotFoundException.php
  app/Http/Controllers/Api/DislikeController.php
  app/Http/Controllers/Api/LikeController.php
  app/Repositories/UserList/UserListRepository.php
  app/Repositories/UserList/UserListRepositoryInterface.php
  database/migrations/2018_08_02_173354_create_user_lists_table.php
  database/migrations/2018_08_02_173659_create_user_list_places_table.php
  database/seeds/UserListTableSeeder.php
  frontend/build/webpack.dev.conf.js
  routes/api.php
  tests/Feature/Api/Dislike/DislikePlaceApiTest.php
  tests/Feature/Api/Like/LikePlaceApiTest.php
  tests/Unit/Routes/DislikePlaceFeatureRouteTest.php
  tests/Unit/Routes/LikePlaceFeatureRouteTest.php
Labels: enhancement

#54 Implemented user tastes DB and repository
  app/Entities/User/Taste.php
  app/Entities/User/User.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/User/TasteRepository.php
  app/Repositories/User/TasteRepositoryInterface.php
  app/Repositories/User/UserRepository.php
  app/Repositories/User/UserRepositoryInterface.php
  database/factories/UserTasteFactory.php
  database/migrations/2018_08_07_080547_create_tastes_table.php
  database/migrations/2018_08_07_081223_create_taste_user_table.php
  database/seeds/UserTasteSeeder.php
  tests/Feature/Repository/UserTastes/UserTastesTest.php
Labels: enhancement

#67 buefy: add buefy UI library
  frontend/src/main.js
  package.json
Labels: enhancement

#73 places: fix PlaceRating namespace and add deleting event
  app/Entities/Place/Place.php
Labels: bug

#72 Feature/user info
  app/Actions/Auth/RegisterUserAction.php
  app/Actions/Auth/Requests/RegisterRequest.php
  app/Entities/User/User.php
  app/Entities/User/UserInfo.php
  app/Http/Controllers/Api/AuthController.php
  app/Http/Requests/Auth/RegisterHttpRequest.php
  app/Repositories/User/UserInfoRepository.php
  app/Repositories/User/UserInfoRepositoryInterface.php
  database/factories/UserFactory.php
  database/factories/UserInfoFactory.php
  database/migrations/2018_08_06_142555_create_user_info_table.php
  database/migrations/2018_08_06_143412_remove_name_from_user_table.php
  database/seeds/UserTableSeeder.php
  tests/Feature/Api/Auth/AuthTest.php
  tests/Unit/Auth/DtoTest.php
  tests/Unit/Auth/PresenterTest.php
Labels: enhancement

#78 change-rating-value-decimal: change migration
  database/migrations/2018_08_06_065718_create_place_rating_table.php
Labels: bug

#79 Hotfix/checked places
  app/Entities/Place/Checkin.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/Place/CheckinRepository.php
  app/Repositories/Place/CheckinRepositoryInterface.php
  database/factories/PlaceCheckinFactory.php
  database/migrations/2018_08_05_145124_create_user_place_checkin_table.php
  database/seeds/PlacesCheckTableSeeder.php
Labels: enhancement

#77 Feature/user_info: User Info Migration update
  database/migrations/2018_08_08_071834_change_name_fields_in_user_info_table.php
Labels: enhancement

#57 Feature/review api endpoints.
  app/Actions/Review/CreateReviewAction.php
  app/Actions/Review/CreateReviewRequest.php
  app/Actions/Review/CreateReviewResponse.php
  app/Actions/Review/DeleteReviewAction.php
  app/Actions/Review/DeleteReviewRequest.php
  app/Actions/Review/GetReviewAction.php
  app/Actions/Review/GetReviewCollectionAction.php
  app/Actions/Review/GetReviewCollectionResponse.php
  app/Actions/Review/GetReviewRequest.php
  app/Actions/Review/GetReviewResponse.php
  app/Actions/Review/UpdateReviewDescriptionAction.php
  app/Actions/Review/UpdateReviewDescriptionRequest.php
  app/Actions/Review/UpdateReviewDescriptionResponse.php
  app/Exceptions/Review/ReviewNotFoundException.php
  app/Exceptions/User/UserNotFoundException.php
  app/Http/Controllers/Api/Review/ReviewController.php
  app/Http/Requests/Review/SaveReviewRequest.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/Review/ReviewRepository.php
  app/Repositories/Review/ReviewRepositoryInterface.php
  routes/api.php
  tests/Feature/Api/Review/ReviewApiTest.php
Labels: enhancement

#83 Fix axios baseUrl value
  frontend/src/services/common/httpService.js
Labels: bug

#100 hotfix: add missed store
  frontend/src/main.js
Labels: bug

#93 hotfix/getters_error: fix vuex getters error
  frontend/src/store/modules/auth/index.js
Labels: bug

#92 add-place-info-migration: add migration
  database/migrations/2018_08_08_173855_create_place_info_table.php
Labels: enhancement

#90 hotfix/place_features_controller_test
  tests/Feature/Api/Place/PlaceFeaturesControllerTest.php
Labels: bug

#81 Feature/attach place users list api
  app/Actions/UserList/Places/AttachPlaceAction.php
  app/Actions/UserList/Places/AttachPlaceRequest.php
  app/Actions/UserList/Places/AttachPlaceResponse.php
  app/Entities/UserList/UserList.php
  app/Exceptions/NonAuthorizedException.php
  app/Exceptions/Place/PlaceNotFoundException.php
  app/Exceptions/UserList/UserListNotFoundException.php
  app/Http/Controllers/Api/UserList/UserListPlaceController.php
  app/Http/Requests/UserList/AttachPlaceHttpRequest.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/Place/PlaceRepository.php
  app/Repositories/UserList/UserListRepository.php
  routes/api.php
  tests/Feature/Api/UserList/UserListAttachPlaceApiTest.php
Labels: enhancement

#88 hotfix/jwt_test_case_class_deprecation
  tests/JwtTestCase.php
Labels: bug

#104 Fix wrong ReviewController namespace.
  app/Http/Controllers/Api/Review/ReviewController.php
  routes/api.php
Labels: invalid

#102 editConfig: edit vuex and router config
  frontend/src/router/index.js
  frontend/src/store/index.js
Labels: enhancement

#71 Feature/review like api endpoints
  app/Actions/Dislike/DislikeReviewAction.php
  app/Actions/Dislike/DislikeReviewRequest.php
  app/Actions/Dislike/DislikeReviewResponse.php
  app/Actions/Like/LikeReviewAction.php
  app/Actions/Like/LikeReviewRequest.php
  app/Actions/Like/LikeReviewResponse.php
  app/Http/Controllers/Api/DislikeController.php
  app/Http/Controllers/Api/LikeController.php
  app/Repositories/Dislike/DislikeReviewCriteria.php
  app/Repositories/Like/LikeReviewCriteria.php
  database/factories/DislikeFactory.php
  database/factories/LikeFactory.php
  database/factories/ReviewFactory.php
  frontend/src/components/PlacesList/PlaceListComponent.vue
  frontend/src/components/PlacesList/PlacesList.vue
  routes/api.php
  tests/Feature/Api/Dislike/DislikeReviewApiTest.php
  tests/Feature/Api/Like/LikeReviewApiTest.php
Labels: enhancement

#112 remove JwtTestCase and replace it to ApiTestCase from depended classes
  tests/Feature/Api/UserList/UserListApiTest.php
  tests/JwtTestCase.php
Labels: enhancement

#105 install league/flysystem-aws-s3-v3
  composer.json
  composer.lock
Labels: enhancement

#94 locationService: add stub retrieving location data
  frontend/src/services/location/locationService.js
  package.json
  yarn.lock
Labels: enhancement

#115 Added default redirect to index page except 'api', 'dist/*', 'storage/*'.
  routes/web.php
Labels: bug

#117 Feature/frontend add auth middleware
  frontend/src/router/index.js
  frontend/src/router/middlewares.js
Labels: enhancement

#118 Hotfix/auth middleware
  frontend/src/router/middlewares.js
Labels: bug

#110 add gd extension in docker file
  docker/php-fpm/Dockerfile
Labels: enhancement

#86 Feature/place migration add fields
  app/Actions/Place/AddPlace/AddPlaceAction.php
  app/Actions/Place/AddPlace/AddPlacePresenter.php
  app/Actions/Place/AddPlace/AddPlaceRequest.php
  app/Actions/Place/AddPlace/AddPlaceResponse.php
  app/Actions/Place/GetPlaceItem/GetPlaceItemPresenter.php
  app/Actions/Place/GetPlaceItem/GetPlaceItemResponse.php
  app/Actions/Place/UpdatePlace/UpdatePlaceAction.php
  app/Actions/Place/UpdatePlace/UpdatePlacePresenter.php
  app/Actions/Place/UpdatePlace/UpdatePlaceRequest.php
  app/Actions/Place/UpdatePlace/UpdatePlaceResponse.php
  app/Entities/Place/Place.php
  app/Http/Controllers/Api/Places/PlaceController.php
  database/factories/PlaceFactory.php
  database/migrations/2018_08_03_054359_create_places_table.php
  tests/Feature/Api/Place/PlaceControllerTest.php
Labels: enhancement

#74 Feature/places rates api endpoints
  app/Actions/Place/Rate/Exceptions/PlaceRatingMinMaxException.php
  app/Actions/Place/Rate/Exceptions/PlaceRatingNotFoundException.php
  app/Actions/Place/Rate/GetPlaceRatingAction.php
  app/Actions/Place/Rate/GetPlaceRatingAvgAction.php
  app/Actions/Place/Rate/GetPlaceRatingAvgRequest.php
  app/Actions/Place/Rate/GetPlaceRatingAvgResponse.php
  app/Actions/Place/Rate/GetPlaceRatingRequest.php
  app/Actions/Place/Rate/GetPlaceRatingResponse.php
  app/Actions/Place/Rate/SetPlaceRatingAction.php
  app/Actions/Place/Rate/SetPlaceRatingRequest.php
  app/Actions/Place/Rate/SetPlaceRatingResponse.php
  app/Http/Controllers/Api/Places/PlaceRatingController.php
  app/Http/Requests/Place/Rate/GetRatingHttpRequest.php
  app/Http/Requests/Place/Rate/SetRatingHttpRequest.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/Place/PlaceRatingRepository.php
  app/Repositories/Place/PlaceRatingRepositoryInterface.php
  database/factories/PlaceRatingFactory.php
  database/seeds/PlaceRatingTableSeeder.php
  routes/api.php
  tests/Feature/Api/Place/PlaceRatingTest.php
  tests/Unit/Routes/PlaceRatingRoutesTest.php
Labels: enhancement

#120 Bug/likes dislike handle
  app/Actions/Dislike/DislikePlaceAction.php
  app/Actions/Like/LikePlaceAction.php
  app/Events/Dislike/DislikeAddEvent.php
  app/Events/Like/LikeAddEvent.php
  app/Listeners/DislikeAddEventListener.php
  app/Listeners/LikeAddEventListener.php
  app/Providers/EventServiceProvider.php
  tests/Feature/Api/Like/LikePlaceApiTest.php
Labels: bug

#123 fix/place-controller_test: fix according to new rules for phone/website
  tests/Feature/Api/Place/PlaceControllerTest.php
Labels: bug

#85 feature/place_checkin_api_end_point
  app/Actions/Place/Checkin/Criteria/UserIdAndPlaceIdCriteria.php
  app/Actions/Place/Checkin/SetCheckinAction.php
  app/Actions/Place/Checkin/SetCheckinRequest.php
  app/Actions/Place/Checkin/SetCheckinResponse.php
  app/Exceptions/User/UserNotFoundException.php
  app/Http/Controllers/Api/Places/PlaceCheckinController.php
  app/Http/Requests/Place/Checkin/SetCheckinHttpRequest.php
  routes/api.php
  tests/Feature/Api/Place/CheckinTest.php
  tests/Unit/Routes/CheckinRoutesTest.php
Labels: enhancement

#113 Hotfix/user name registration
  app/Actions/Auth/RegisterUserAction.php
  app/Actions/Auth/Requests/RegisterRequest.php
  app/Http/Controllers/Api/Auth/AuthController.php
  app/Http/Requests/Auth/RegisterHttpRequest.php
  app/Providers/RepositoryServiceProvider.php
  tests/Feature/Api/Auth/AuthTest.php
  tests/Unit/Auth/ActionTest.php
  tests/Unit/Auth/DtoTest.php
Labels: bug

#89 Auth pages mockups
  frontend/src/App.vue
  frontend/src/components/auth/Container.vue
  frontend/src/components/auth/Form.vue
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/Recover.vue
  frontend/src/components/auth/Reset.vue
  frontend/src/components/auth/SignUp.vue
  frontend/src/router/index.js
  resources/views/index.blade.php
Labels: enhancement

#126 Move state to store/common into different files.
  frontend/src/state/index.js
  frontend/src/store/common/actions.js
  frontend/src/store/common/getters.js
  frontend/src/store/common/mutations.js
  frontend/src/store/common/state.js
  frontend/src/store/index.js
Labels: bug

#84 Feature/frontend review list
  frontend/src/components/review/ReviewList.vue
  frontend/src/components/review/ReviewListElement.vue
  frontend/src/router/index.js
  resources/views/index.blade.php
Labels: enhancement

#127 Edit category list in PlaceCategoryTableSeeder.
  database/seeds/PlaceCategoryTableSeeder.php
Labels: enhancement

#134 Feature/frontend user tastes
  frontend/src/App.vue
  frontend/src/components/tastes/TastesAdd.vue
  frontend/src/router/index.js
Labels: enhancement, frontend

#135 ReviewList include into PlacePage.
  frontend/src/components/review/ReviewList.vue
  frontend/src/pages/PlacePage.vue
Labels: enhancement

#138 fix/place_rating_route
  routes/api.php
  tests/Feature/Api/Place/PlaceRatingTest.php
  tests/Unit/Routes/PlaceRatingRoutesTest.php
Labels: bug

#106 feature/refresh_jwt_token_processing
  app/Http/Controllers/Api/Auth/AuthController.php
  app/Http/Kernel.php
  app/Http/Middleware/JwtAuthenticate.php
  routes/api.php
Labels: enhancement

#122 Feature/auth pages logic
  frontend/src/App.vue
  frontend/src/components/auth/Container.vue
  frontend/src/components/auth/Form.vue
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/Recover.vue
  frontend/src/components/auth/Reset.vue
  frontend/src/components/auth/SignUp.vue
  frontend/src/main.js
  frontend/src/pages/LoginPage.vue
  frontend/src/pages/RecoverPasswordPage.vue
  frontend/src/pages/ResetPasswordPage.vue
  frontend/src/pages/SignUpPage.vue
  frontend/src/router/index.js
  frontend/src/services/common/httpService.js
  frontend/src/store/modules/auth/actions.js
  frontend/src/store/modules/auth/mutations.js
  package.json
  yarn.lock
Labels: enhancement

#65 Feature/review upload photo api
  .circleci/config.yml
  .gitignore
  app/Actions/Review/DeleteReviewPhotoAction.php
  app/Actions/Review/DeleteReviewPhotoRequest.php
  app/Actions/Review/GetReviewPhotoByReviewAction.php
  app/Actions/Review/GetReviewPhotoByReviewRequest.php
  app/Actions/Review/GetReviewPhotoByReviewResponse.php
  app/Actions/Review/SaveReviewPhotoAction.php
  app/Actions/Review/SaveReviewPhotoRequest.php
  app/Actions/Review/SaveReviewPhotoResponse.php
  app/Exceptions/Review/ReviewPhotoExistsException.php
  app/Http/Controllers/Api/Review/ReviewController.php
  app/Http/Controllers/Api/Review/ReviewPhotoController.php
  app/Http/Requests/Review/ReviewPhotoRequest.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/Review/ReviewPhotoRepository.php
  app/Repositories/Review/ReviewPhotoRepositoryInterface.php
  database/factories/Review.php
  database/factories/ReviewPhotoFactory.php
  database/seeds/ReviewPhotoTableSeeder.php
  routes/api.php
  tests/Feature/Api/Review/ReviewApiTest.php
  tests/Feature/Api/Review/ReviewPhotoApiTest.php
Labels: enhancement

#133 Implement user's list page mockup
  frontend/src/App.vue
  frontend/src/components/userLists/UserListsItem.vue
  frontend/src/components/userLists/UserListsList.vue
  frontend/src/pages/UserListsPage.vue
  frontend/src/router/index.js
Labels: enhancement, frontend

#116 Feature/user info api
  app/Actions/User/GetUserInfoAction.php
  app/Actions/User/GetUserInfoRequest.php
  app/Actions/User/GetUserInfoResponse.php
  app/Actions/User/SaveUserInfoAction.php
  app/Actions/User/SaveUserInfoRequest.php
  app/Actions/User/SaveUserInfoResponse.php
  app/Entities/User/UserInfo.php
  app/Exceptions/UserInfoExceptions/UserInfoNotValidSocialUrlException.php
  app/Exceptions/UserInfoExceptions/UserInfoRequiredFieldsException.php
  app/Http/Controllers/Api/Users/UserInfoController.php
  app/Http/Requests/User/UserInfoHttpRequest.php
  app/Providers/RepositoryServiceProvider.php
  routes/api.php
  tests/Feature/Api/UserInfo/UserInfoApiTest.php
Labels: enhancement

#141 fix
  frontend/src/App.vue
Labels: bug

#143 Hotfix/me route current user
  app/Actions/Auth/GetUserAction.php
  app/Actions/Auth/Presenters/AuthPresenter.php
  app/Actions/Auth/Requests/GetUserRequest.php
  app/Actions/Auth/Responses/GetUserResponse.php
  app/Exceptions/Auth/InvalidUserDataException.php
  app/Http/Controllers/Api/Auth/AuthController.php
  tests/Feature/Api/Auth/AuthTest.php
  tests/Feature/Api/Auth/ResetPasswordTest.php
  tests/Unit/Auth/AuthPresenterTest.php
Labels: bug

#147 top_navbar_mockup: add navbar component. Remove navigation from App.vue
  frontend/src/App.vue
  frontend/src/assets/icon-notifications.png
  frontend/src/components/navbar/TopNavbar.vue
Labels: enhancement, frontend

#146 Fix UX on the auth pages
  composer.lock
  frontend/src/App.vue
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/SignUp.vue
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/services/common/httpService.js
  frontend/src/store/modules/auth/actions.js
Labels: enhancement, frontend

#153 rename frontend dirs
  frontend/src/components/place/SearchPlace.vue
  frontend/src/components/placesList/PlaceListComponent.vue
  frontend/src/components/placesList/PlacesList.vue
  frontend/src/components/taste/TastesAdd.vue
  frontend/src/components/userList/UserListsItem.vue
  frontend/src/components/userList/UserListsList.vue
  frontend/src/pages/UserListsPage.vue
  frontend/src/router/index.js
Labels: frontend

#154 Hotfix/signup validation firstname lastname required
  frontend/src/components/auth/SignUp.vue
Labels: bug, frontend

#132 Remove HelloWorld.vue and logo from project.
  frontend/src/assets/logo.png
  frontend/src/components/HelloWorld.vue
  frontend/src/router/index.js
Labels: enhancement

#157 Create abstract DomainException class
  app/Actions/Place/Rate/Exceptions/PlaceRatingMinMaxException.php
  app/Actions/Place/Rate/Exceptions/PlaceRatingNotFoundException.php
  app/Actions/Place/SpecialFeature/Exceptions/PlaceFeatureNotFoundException.php
  app/Exceptions/Auth/EmailAlreadyExistsException.php
  app/Exceptions/Auth/InvalidUserDataException.php
  app/Exceptions/Auth/PasswordResetEmailSentException.php
  app/Exceptions/Auth/PasswordResetFailedException.php
  app/Exceptions/Auth/PasswordsDosentMatchException.php
  app/Exceptions/DomainException.php
  app/Exceptions/NonAuthorizedException.php
  app/Exceptions/Place/PlaceNotFoundException.php
  app/Exceptions/PlaceExceptions/PlaceCategoryDoesNotExistException.php
  app/Exceptions/PlaceExceptions/PlaceCityDoesNotExistException.php
  app/Exceptions/PlaceExceptions/PlaceCreatorDoesNotExistException.php
  app/Exceptions/PlaceExceptions/PlaceDoesNotExistException.php
  app/Exceptions/PlaceExceptions/PlaceLocationInvalidException.php
  app/Exceptions/Review/ReviewNotFoundException.php
  app/Exceptions/Review/ReviewPhotoExistsException.php
  app/Exceptions/User/UserNotFoundException.php
  app/Exceptions/UserInfoExceptions/UserInfoNotValidSocialUrlException.php
  app/Exceptions/UserInfoExceptions/UserInfoRequiredFieldsException.php
  app/Exceptions/UserList/UserListNotFoundException.php
  app/Exceptions/UserListExceptions/UserListExistsException.php
  app/Exceptions/UserTaste/TasteNotFoundException.php
Labels: enhancement

#158 add padding
  frontend/src/components/auth/Container.vue
Labels: frontend

#150 Fix/user info api minor refactoring
  app/Actions/User/SaveUserInfoAction.php
  app/Actions/User/SaveUserInfoRequest.php
  app/Http/Controllers/Api/Users/UserInfoController.php
  tests/Feature/Api/UserInfo/UserInfoApiTest.php
Labels: enhancement

#152 Feature/frontend add list page
  frontend/src/App.vue
  frontend/src/assets/no-photo.png
  frontend/src/components/userList/UserListAdd.vue
  frontend/src/main.js
  frontend/src/pages/UserListAddPage.vue
  frontend/src/router/index.js
  package.json
  yarn.lock
Labels: enhancement

#167 toast: change modal to toast on signup and login pages
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/SignUp.vue
Labels: enhancement, frontend

#168 Added white background
  frontend/src/components/placesList/PlaceListComponent.vue
Labels: bug, frontend

#169 hotfix/place-list_wrong_places: use places from state
  frontend/src/components/placesList/PlacesList.vue
Labels: bug, frontend

#165 frontend: add place review photos
  frontend/src/components/place/PlaceTopInfo.vue
  frontend/src/components/placesList/ReviewPhoto.vue
  frontend/src/components/placesList/ReviewsPhotos.vue
  frontend/src/components/review/ReviewPhoto.vue
  frontend/src/components/review/ReviewPhotoGallery.vue
  frontend/src/pages/PlacePage.vue
Labels: enhancement, frontend

#173 History page styles
  frontend/src/components/place/PlaceVisitedPreview.vue
  frontend/src/pages/HistoryPage.vue
Labels: frontend

#144 hotfix/move_token_to_local-storage
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/router/middlewares.js
  frontend/src/services/common/storageService.js
  frontend/src/store/modules/auth/getters.js
  frontend/src/store/modules/auth/mutations.js
  frontend/src/store/modules/auth/state.js
Labels: bug

#184 Feature/eslint fix code
  .eslintrc.js
  frontend/src/App.vue
  frontend/src/components/auth/Container.vue
  frontend/src/components/auth/Form.vue
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/Recover.vue
  frontend/src/components/auth/Reset.vue
  frontend/src/components/auth/SignUp.vue
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/components/place/PlacePhoto.vue
  frontend/src/components/place/PlacePhotoList.vue
  frontend/src/components/place/PlaceSidebarInfo.vue
  frontend/src/components/place/PlaceTopInfo.vue
  frontend/src/components/place/PlaceVisitedPreview.vue
  frontend/src/components/place/SearchPlace.vue
  frontend/src/components/placesList/PlaceListComponent.vue
  frontend/src/components/placesList/PlacesList.vue
  frontend/src/components/placesList/ReviewPhoto.vue
  frontend/src/components/placesList/ReviewsPhotos.vue
  frontend/src/components/profile/EditProfile.vue
  frontend/src/components/review/ReviewList.vue
  frontend/src/components/review/ReviewListElement.vue
  frontend/src/components/review/ReviewPhoto.vue
  frontend/src/components/review/ReviewPhotoGallery.vue
  frontend/src/components/taste/TasteList.vue
  frontend/src/components/userList/UserListAdd.vue
  frontend/src/components/userList/UserListsItem.vue
  frontend/src/components/userList/UserListsList.vue
  frontend/src/main.js
  frontend/src/pages/HistoryPage.vue
  frontend/src/pages/LoginPage.vue
  frontend/src/pages/MyTastesPage.vue
  frontend/src/pages/PlacePage.vue
  frontend/src/pages/ProfilePage.vue
  frontend/src/pages/RecoverPasswordPage.vue
  frontend/src/pages/ResetPasswordPage.vue
  frontend/src/pages/SeachPlacePage.vue
  frontend/src/pages/SignUpPage.vue
  frontend/src/pages/UserListAddPage.vue
  frontend/src/pages/UserListsPage.vue
  frontend/src/router/middlewares.js
  frontend/src/services/common/httpService.js
  frontend/src/services/location/locationService.js
  frontend/src/store/common/actions.js
  frontend/src/store/common/getters.js
  frontend/src/store/common/mutations.js
  frontend/src/store/common/state.js
  frontend/src/store/modules/auth/actions.js
  frontend/src/store/modules/auth/getters.js
  frontend/src/store/modules/auth/state.js
  frontend/src/store/modules/map/actions.js
  frontend/src/store/modules/map/getters.js
  package.json
Labels: enhancement

#176 Feature/add place page mockup
  frontend/src/pages/NewPlacePage.vue
  frontend/src/router/index.js
Labels: enhancement, frontend

#174 change controllers namespaces
  app/Http/Controllers/Api/Like/DislikeController.php
  app/Http/Controllers/Api/Like/LikeController.php
  app/Http/Controllers/Api/Place/PlaceCheckinController.php
  app/Http/Controllers/Api/Place/PlaceController.php
  app/Http/Controllers/Api/Place/PlaceFeaturesController.php
  app/Http/Controllers/Api/Place/PlaceRatingController.php
  app/Http/Controllers/Api/User/UserInfoController.php
  app/Http/Controllers/Api/User/UserList/UserListController.php
  app/Http/Controllers/Api/User/UserList/UserListPlaceController.php
  app/Http/Controllers/Api/User/UserTaste/TasteController.php
  routes/api.php
Labels: enhancement

#191 fix: remove FOREIGN_KEY_CHECKS from seeders
  database/seeds/CityTableSeeder.php
  database/seeds/PlaceCategoriesAttachTagsSeeder.php
  database/seeds/PlaceCategoriesTagsTableSeeder.php
  database/seeds/PlaceCategoryTableSeeder.php
  database/seeds/PlaceRatingTableSeeder.php
  database/seeds/PlaceTableSeeder.php
  database/seeds/PlacesFeaturesTableSeeder.php
  database/seeds/UserTableSeeder.php
Labels: bug

#196 hotfix/review-list_not_defined: fixed
  frontend/src/router/index.js
Labels: bug, hotfix

#187 login_form: fix responsive markup
  frontend/src/components/auth/Container.vue
  frontend/src/components/navbar/TopNavbar.vue
Labels: bug, frontend

#182 Feature/top navbar user info
  app/Actions/Auth/Presenters/AuthPresenter.php
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/store/modules/auth/state.js
Labels: enhancement, frontend

#197 navbar: add history menu item
  frontend/src/components/navbar/TopNavbar.vue
Labels: enhancement, frontend

#195 AuthErrorMessage: change authorization error message
  frontend/src/components/auth/Login.vue
Labels: enhancement

#177 feature/Zoom map to current user location
  frontend/src/components/place/SearchPlace.vue
  frontend/src/services/location/locationService.js
  package.json
  yarn.lock
Labels: enhancement, frontend

#193 Feature/markers for places on map
  frontend/src/assets/test_icon.svg
  frontend/src/components/place/SearchPlace.vue
  frontend/src/services/location/locationService.js
  frontend/src/services/map/markerGeneratorService.js
  frontend/src/services/map/markerManagerService.js
  frontend/src/store/modules/place/state.js
  yarn.lock
Labels: enhancement, frontend

#202 remove icon bell
  frontend/src/components/placesList/PlaceListComponent.vue
Labels: frontend

#199 Hotfix/navbar: fix navbar user and menu
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/services/common/storageService.js
Labels: bug, frontend

#201 Feature/frontend show categories in searh input
  app/Actions/Place/GetPlaceCategoryByName/GetPlaceCategoryByNameRequest.php
  app/Http/Controllers/Api/Place/PlaceCategoryController.php
  frontend/src/components/auth/Login.vue
  frontend/src/components/navbar/SearchInput.vue
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/pages/NewPlacePage.vue
  frontend/src/store/index.js
  frontend/src/store/modules/auth/state.js
  frontend/src/store/modules/place/category/actions.js
  frontend/src/store/modules/place/category/index.js
  frontend/src/store/modules/place/category/mutations.js
  frontend/src/store/modules/place/category/state.js
  routes/api.php
Labels: enhancement

#203 Fix styles for my places page
  frontend/src/components/place/PlaceList.vue
  frontend/src/components/place/PlacePreviewList.vue
  frontend/src/components/place/SearchPlace.vue
  frontend/src/components/placesList/ReviewPhoto.vue
  frontend/src/components/placesList/ReviewsPhotos.vue
  frontend/src/pages/PlaceListPage.vue
  frontend/src/router/index.js
Labels: frontend

#208 hotfix
  frontend/src/components/place/PlaceList.vue
  frontend/src/components/place/PlacePreviewList.vue
  frontend/src/services/map/markerManagerService.js
Labels: bug

#207 Fix/auth namespace
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/Recover.vue
  frontend/src/components/auth/Reset.vue
  frontend/src/components/auth/SignUp.vue
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/router/middlewares.js
  frontend/src/store/index.js
  frontend/src/store/modules/auth/index.js
Labels: bug

#185 Feature/like dislike logic
  app/Actions/Like/GetLikedPlaceAction.php
  app/Actions/Like/GetLikedPlaceRequest.php
  app/Actions/Like/GetLikedPlaceResponse.php
  app/Entities/Like/LikeStatus.php
  app/Http/Controllers/Api/Like/LikeController.php
  routes/api.php
  tests/Feature/Api/Like/LikePlaceApiTest.php
Labels: enhancement

#181 Fix/auth flow
  app/Http/Middleware/JwtAuthenticate.php
  frontend/src/router/middlewares.js
  frontend/src/services/common/httpService.js
  frontend/src/services/common/storageService.js
  frontend/src/store/common/actions.js
  frontend/src/store/common/getters.js
  frontend/src/store/common/mutations.js
  frontend/src/store/common/state.js
  frontend/src/store/modules/auth/actions.js
  frontend/src/store/modules/auth/getters.js
  frontend/src/store/modules/auth/mutations.js
Labels: enhancement, frontend

#211 Hotfix/search place fixes
  frontend/src/components/place/PlacePreviewList.vue
  frontend/src/components/place/SearchPlace.vue
Labels: bug, frontend

#210 add buefy autocomplete
  frontend/src/components/navbar/SearchInput.vue
Labels: enhancement, frontend

#198 Feature/check email unique and validation messages on signup
  app/Actions/Auth/CheckEmailUniqueAction.php
  app/Actions/Auth/Requests/CheckEmailUniqueRequest.php
  app/Actions/Auth/Responses/CheckEmailUniqueResponse.php
  app/Http/Controllers/Api/Auth/AuthController.php
  app/Http/Requests/Auth/CheckEmailUniqueHttpRequest.php
  app/Repositories/User/UserRepository.php
  frontend/src/components/auth/SignUp.vue
  frontend/src/store/modules/auth/actions.js
  routes/api.php
Labels: bug, enhancement

#216 fix/login_to_account_on_enter_btn_pressed
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/SignUp.vue
Labels: bug, frontend

#214 hotfix/fix_signup_auth_namespace
  frontend/src/components/auth/SignUp.vue
Labels: bug, frontend, hotfix

#213 Fix design of User lists page
  frontend/src/components/userList/UserListsItem.vue
  frontend/src/components/userList/UserListsList.vue
Labels: bug, frontend

#229 history page responsive
  frontend/src/components/place/PlaceVisitedPreview.vue
  frontend/src/pages/HistoryPage.vue
Labels: bug, frontend

#227 Fix/switch case
  frontend/src/components/place/PlaceCheckinModal.vue
  frontend/src/store/modules/place/actions.js
Labels: bug

#226 Fix/place details page responsive
  frontend/src/components/place/PlacePhotoList.vue
  frontend/src/components/place/PlaceTopInfo.vue
Labels: bug, frontend

#222 Added field for menu link.
  frontend/src/pages/NewPlacePage.vue
Labels: enhancement, frontend

#232 Fix/search page responsive
  frontend/src/components/place/SearchPlace.vue
Labels: bug, frontend

#190 Feature/save place to user list
  frontend/src/components/place/PlaceTopInfo.vue
  frontend/src/store/index.js
  frontend/src/store/modules/userList/actions.js
  frontend/src/store/modules/userList/index.js
Labels: enhancement, frontend

#221 update place photo
  app/Actions/Place/GetPlaceCollection/GetPlaceCollectionPresenter.php
  app/Entities/Place/PlacePhoto.php
  database/factories/PlacePhotoFactory.php
  database/seeds/PlaceTableSeeder.php
Labels: enhancement

#228 Photo: add dimensions to db
  app/Actions/Review/SaveReviewPhotoAction.php
  app/Http/Requests/Review/ReviewPhotoRequest.php
  database/factories/ReviewPhotoFactory.php
  database/migrations/2018_08_16_120244_add_height_and_width_to_photos_tables.php
Labels: in progress

#230 Fix/profile page responsive
  frontend/src/components/profile/EditProfile.vue
Labels: bug, frontend

#236 hotfix search page map
  frontend/src/components/place/SearchPlace.vue
Labels: bug, frontend

#241 change button when hovered
  frontend/src/components/taste/TasteList.vue
Labels: bug, frontend

#218 Hotfix/marker manager service invisible markers
  frontend/src/components/place/SearchPlace.vue
  frontend/src/services/map/markerManagerService.js
Labels: frontend, hotfix

#220 Uncorrect handle of signup/logout/login (auth actions)
  frontend/src/components/auth/Login.vue
  frontend/src/components/auth/SignUp.vue
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/store/modules/auth/actions.js
Labels: bug, frontend

#225 photo-gallery: add VueImg library
  frontend/src/components/place/PlacePhoto.vue
  frontend/src/components/review/ReviewPhoto.vue
  frontend/src/main.js
  package.json
  yarn.lock
Labels: frontend

#231 Feature/add review frontend component
  app/Actions/Place/GetPlaceCollection/GetPlaceCollectionPresenter.php
  app/Actions/Review/SaveReviewPhotoAction.php
  app/Repositories/Place/PlaceRepository.php
  app/Services/FileNameGenerator.php
  frontend/src/components/review/AddReview.vue
  frontend/src/components/review/ReviewList.vue
  frontend/src/store/index.js
  frontend/src/store/modules/review/actions.js
  frontend/src/store/modules/review/index.js
  public/assets/add_review_default_avatar.png
Labels: enhancement, frontend

#242 map displayed at the top of page
  frontend/src/pages/HistoryPage.vue
Labels: bug, frontend

#240 Feature/fit map by markers
  database/factories/PlaceFactory.php
  database/migrations/2018_08_03_054359_create_places_table.php
  database/seeds/PlaceTableSeeder.php
  database/seeds/UserTableSeeder.php
  frontend/src/assets/user-placeholder.jpg
  frontend/src/components/place/SearchPlace.vue
  frontend/src/services/map/markerManagerService.js
  package.json
  yarn.lock
Labels: enhancement, frontend

#235 Feature/navbar_search_city: Implement cities autocomplete
  frontend/src/components/navbar/NavbarSearchPanel.vue
  frontend/src/components/navbar/SearchCity.vue
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/services/location/locationService.js
  frontend/src/store/index.js
  frontend/src/store/modules/search/actions.js
  frontend/src/store/modules/search/index.js
  frontend/src/store/modules/search/mutations.js
  frontend/src/store/modules/search/state.js
Labels: enhancement, frontend

#263 GetLocationPlace : Add method getLocation into Place model
  app/Entities/Place/Location.php
  app/Entities/Place/Place.php
Labels: backend

#247 Feature/edit add list page mockup
  frontend/src/components/userList/UserListAdd.vue
Labels: frontend

#256 Feature/show real profile data
  app/Actions/Auth/Presenters/AuthPresenter.php
  frontend/src/components/profile/EditProfile.vue
Labels: frontend

#258 change places/list to /my-places
  frontend/src/router/index.js
Labels: bug, frontend

#260 Fix/add my tastes route and top menu link
  frontend/src/components/navbar/TopNavbar.vue
  frontend/src/router/index.js
Labels: enhancement, frontend

#252 Fix/place title is not displayed in item
  app/Actions/Place/GetPlaceItem/GetPlaceItemPresenter.php
  app/Entities/Localization/PlaceTranslation.php
  frontend/src/components/place/PlaceTopInfo.vue
Labels: bug, frontend

#253 Feature/find places by coordinates method
  app/Repositories/Place/PlaceRepository.php
  app/Repositories/Place/PlaceRepositoryInterface.php
  tests/Feature/Repository/Place/PlaceRepositoryTest.php
Labels: backend, enhancement

#255 fix/list_photo_is_displayed_too_big
  frontend/src/components/userList/UserListsItem.vue
  package.json
  yarn.lock
Labels: bug, frontend

#254 Add API endpoints to get Category Tags.
  app/Actions/Place/GetPlaceTagsByCategory/GetPlaceTagsByCategoryAction.php
  app/Actions/Place/GetPlaceTagsByCategory/GetPlaceTagsByCategoryRequest.php
  app/Actions/Place/GetPlaceTagsByCategory/GetPlaceTagsByCategoryResponse.php
  app/Http/Controllers/Api/Place/PlaceCategoryTagsController.php
  app/Repositories/Place/PlaceCategoryTagRepository.php
  app/Repositories/Place/PlaceCategoryTagRepositoryInterface.php
  database/factories/PlaceCategoriesTagsFactory.php
  frontend/src/components/place/AddPlace.vue
  frontend/src/pages/NewPlacePage.vue
  frontend/src/store/modules/place/category/actions.js
  routes/api.php
  tests/Feature/Api/Place/PlaceCategoryTagsControllerTest.php
Labels: backend, enhancement

#267 Feature/navbar: make search button clickable
  frontend/src/components/navbar/NavbarSearchPanel.vue
  frontend/src/components/navbar/SearchCity.vue
Labels: enhancement, frontend

#268 Remove link to my places from menu
  frontend/src/components/navbar/TopNavbar.vue
Labels: frontend

#269 fix/navbar_search_city: minor fix in SearchCityComponent
  frontend/src/components/navbar/NavbarSearchPanel.vue
  frontend/src/components/navbar/SearchCity.vue
Labels: bug, frontend

#270 Remove non-food seeds
  database/seeds/PlaceCategoriesAttachTagsSeeder.php
  database/seeds/PlaceCategoriesTagsTableSeeder.php
  database/seeds/PlaceCategoryTableSeeder.php
  database/seeds/UserListTableSeeder.php
  database/seeds/UserTasteSeeder.php
Labels: backend

#273 change img_url in PlaceTableSeeder
  database/seeds/PlaceTableSeeder.php
Labels: enhancement

#244 Photos tab on the place page
  database/factories/PlacePhotoFactory.php
  database/factories/ReviewFactory.php
  database/factories/ReviewPhotoFactory.php
  database/seeds/PlaceTableSeeder.php
  frontend/src/components/place/PlacePhoto.vue
  frontend/src/components/place/PlacePhotoList.vue
  frontend/src/components/place/PlaceTopInfo.vue
  frontend/src/components/review/ReviewPhoto.vue
Labels: bug

#264 Search Place photo: Show Image on search grid items
  frontend/src/assets/placeholder_128x128.png
  frontend/src/components/place/PlacePreview.vue
Labels: bug

#243 GetUsersLists : get user's lists from backend
  frontend/src/components/userList/ListPreview.vue
  frontend/src/components/userList/ListPreviewItems.vue
  frontend/src/components/userList/UserListsList.vue
  frontend/src/pages/UserListsPage.vue
  frontend/src/store/index.js
  frontend/src/store/modules/userList/actions.js
Labels: enhancement, frontend

#257 Fix navbar menu on small screens
  frontend/src/components/navbar/NavbarSearchPanel.vue
  frontend/src/components/navbar/TopNavbar.vue
Labels: frontend

#266 Feature/normalizer_service: add normalizer service
  frontend/src/services/common/normalizerService.js
Labels: enhancement, frontend

#262 AddRedirect : add redirect.
  frontend/src/router/index.js
Labels: frontend

#271 hotfix/fix-console-error-profile-page
  frontend/src/components/profile/EditProfile.vue
Labels: bug, frontend

#276 Feature/update rating value after checkin
  app/Actions/Place/GetPlaceCollection/GetPlaceCollectionPresenter.php
  app/Actions/Place/GetPlaceItem/GetPlaceItemPresenter.php
  app/Actions/Place/Rate/GetPlaceRatingAction.php
  app/Actions/Place/Rate/SetPlaceRatingAction.php
  app/Actions/Place/Rate/SetPlaceRatingRequest.php
  app/Actions/Place/Rate/SetPlaceRatingResponse.php
  app/Actions/Presenters/Review/ReviewPresenter.php
  app/Http/Controllers/Api/Place/PlaceRatingController.php
  app/Repositories/Place/PlaceRatingRepository.php
  app/Repositories/Place/PlaceRatingRepositoryInterface.php
  frontend/src/components/place/PlaceTopInfo.vue
  frontend/src/pages/PlacePage.vue
  frontend/src/store/modules/place/actions.js
  frontend/src/store/modules/place/mutations.js
  frontend/src/store/modules/place/state.js
Labels: backend, enhancement, frontend

#282 Hotfix/fix likes hover
  app/Actions/Presenters/Review/ReviewPresenter.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ReviewSeeder.php
  frontend/src/components/misc/LikeDislikeButtons.vue
  frontend/src/components/place/PlacePreview.vue
  frontend/src/components/place/PlaceTopInfo.vue
  frontend/src/components/review/PlacePreviewReviewItem.vue
  frontend/src/components/review/ReviewListElement.vue
Labels: bug, frontend

#285 UserListsBackend: hotfix return value in frontend
  frontend/src/store/modules/userList/actions.js
Labels: frontend, hotfix

#281 Frontend: attach categories tags.
  frontend/src/components/place/AddPlace.vue
  frontend/src/store/modules/place/category/actions.js
Labels: enhancement, frontend

#284 FixedNavbar: navbar fixed top position
  frontend/src/components/navbar/TopNavbar.vue
  resources/views/index.blade.php
Labels: frontend

#265 Bug/photos and comments
  app/Actions/Place/GetPlaceItem/GetPlaceItemPresenter.php
  app/Actions/Presenters/Place/PlaceInfoPresenter.php
  app/Entities/Place/Place.php
  app/Entities/Place/PlaceInfo.php
  database/factories/PlaceInfoFactory.php
  database/seeds/PlaceTableSeeder.php
  frontend/src/components/place/PlaceSidebarInfo.vue
Labels: bug

#259 frontend-like-dislike: add actions
  frontend/src/components/misc/LikeDislikeButtons.vue
  frontend/src/components/place/PlaceTopInfo.vue
  frontend/src/store/modules/place/actions.js
  frontend/src/store/modules/place/mutations.js
  frontend/src/store/modules/place/state.js
Labels: frontend

#286 img-placeholder: using local image
  frontend/src/components/place/SearchPlace.vue
  frontend/src/services/map/markerManagerService.js
Labels: bug
